name: Create a zip file

# https://github.com/marketplace/actions/zip-release
on:
  push:
    tags:
      - 'zip*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'carbon.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
