In [1]:
import pandas as pd
from decimal import Decimal

from carbon import CarbonSimulatorUI, __version__, __date__
print(f"Carbon Version v{__version__} ({__date__})", )

Carbon Version v2.2-BETA2 (03/Jan/2022)


# Carbon Simulation - Demo 5-1

## Init 
Evaluate the result of trading on a single order, which

sells 1B USDC at a price of 1500 USDC per ETH (price range is from 1500 to 1000, but the start price, which each one of the trades above goes by, is 1500)

In [2]:
Sim = CarbonSimulatorUI(pair="ETH/USDC", verbose=False, matching_method='exact', raiseonerror=True)
FastSim = CarbonSimulatorUI(pair="ETH/USDC", verbose=False, matching_method='fast', raiseonerror=True)

In [3]:
Sim.add_strategy('USDC', Decimal(1000000000), Decimal(1500), Decimal(1000), 0, None, None)
Sim.state()['orders']

id     pair   tkn         y_int             y y_unit  disabled p_start  \
0   0  ETHUSDC  USDC  1.000000e+09  1.000000e+09   USDC     False  1500.0   
1   1  ETHUSDC   ETH  0.000000e+00  0.000000e+00    ETH      True    None   

    p_end  p_marg        p_unit  lid  
0  1000.0  1500.0  USDC per ETH    1  
1    None    None  USDC per ETH    0

In [4]:
FastSim.add_strategy('USDC', Decimal(1000000000), Decimal(1500), Decimal(1000), 0, None, None)
FastSim.state()['orders']

id     pair   tkn         y_int             y y_unit  disabled p_start  \
0   0  ETHUSDC  USDC  1.000000e+09  1.000000e+09   USDC     False  1500.0   
1   1  ETHUSDC   ETH  0.000000e+00  0.000000e+00    ETH      True    None   

    p_end  p_marg        p_unit  lid  
0  1000.0  1500.0  USDC per ETH    1  
1    None    None  USDC per ETH    0

## Route by Source

#### AMM buys ETH

* tradeBySourceAmount: input =     10.0 ETH , output =   14999.958711 USDC, rate = 1499.9958711
* tradeBySourceAmount: input =    100.0 ETH , output =  149995.871286 USDC, rate = 1499.95871286
* tradeBySourceAmount: input =   1000.0 ETH , output = 1499587.230921 USDC, rate = 1499.587230921

In [5]:
Sim.trader_sells('ETH',Decimal(10), execute=False)
Sim.trader_sells('ETH',Decimal(100), execute=False)
Sim.trader_sells('ETH',Decimal(1000), execute=False)
results = Sim.state()['trades']
assert(f"{results[results.uid=='0']['price'].values[0]:.5f}" == "1499.99587")
assert(f"{results[results.uid=='1']['price'].values[0]:.5f}" == "1499.95871")
assert(f"{results[results.uid=='2']['price'].values[0]:.5f}" == "1499.58723")
# we can see that the output is as expected below
results

uid  id subid                                note   aggr   exec limitfail  \
0  0.0   0     0                            route #0  False  False      None   
0    0   0     A      AMM sells 15000USDC buys 10ETH   True  False      None   
0  1.0   1     0                            route #0  False  False      None   
0    1   1     A    AMM sells 149996USDC buys 100ETH   True  False      None   
0  2.0   2     0                            route #0  False  False      None   
0    2   2     A  AMM sells 1499587USDC buys 1000ETH   True  False      None   

           amt1  tkn1    amt2 tkn2     pair routeix  nroutes        price  \
0  1.499996e+04  USDC    10.0  ETH  ETHUSDC       0        1  1499.995871   
0  1.499996e+04  USDC    10.0  ETH  ETHUSDC     [0]        1  1499.995871   
0  1.499959e+05  USDC   100.0  ETH  ETHUSDC       0        1  1499.958713   
0  1.499959e+05  USDC   100.0  ETH  ETHUSDC     [0]        1  1499.958713   
0  1.499587e+06  USDC  1000.0  ETH  ETHUSDC       0        1  1499.587231   
0  1.499587e+06  USDC  1000.0  ETH  ETHUSDC     [0]        1  1499.587231   

         p_unit  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH

In [6]:
FastSim.trader_sells('ETH',Decimal(10), execute=False)
FastSim.trader_sells('ETH',Decimal(100), execute=False)
FastSim.trader_sells('ETH',Decimal(1000), execute=False)
results = FastSim.state()['trades']
assert(f"{results[results.uid=='0']['price'].values[0]:.5f}" == "1499.99587")
assert(f"{results[results.uid=='1']['price'].values[0]:.5f}" == "1499.95871")
assert(f"{results[results.uid=='2']['price'].values[0]:.5f}" == "1499.58723")
# we can see that the output is as expected below
results

uid  id subid                                note   aggr   exec limitfail  \
0  0.0   0     0                            route #0  False  False      None   
0    0   0     A      AMM sells 15000USDC buys 10ETH   True  False      None   
0  1.0   1     0                            route #0  False  False      None   
0    1   1     A    AMM sells 149996USDC buys 100ETH   True  False      None   
0  2.0   2     0                            route #0  False  False      None   
0    2   2     A  AMM sells 1499587USDC buys 1000ETH   True  False      None   

           amt1  tkn1    amt2 tkn2     pair routeix  nroutes        price  \
0  1.499996e+04  USDC    10.0  ETH  ETHUSDC       0        1  1499.995871   
0  1.499996e+04  USDC    10.0  ETH  ETHUSDC     [0]        1  1499.995871   
0  1.499959e+05  USDC   100.0  ETH  ETHUSDC       0        1  1499.958713   
0  1.499959e+05  USDC   100.0  ETH  ETHUSDC     [0]        1  1499.958713   
0  1.499587e+06  USDC  1000.0  ETH  ETHUSDC       0        1  1499.587231   
0  1.499587e+06  USDC  1000.0  ETH  ETHUSDC     [0]        1  1499.587231   

         p_unit  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH

## Route by Target

#### Trader Buys USDC

* tradeByTargetAmount: input =   1500.0 USDC, output =       1.000001 ETH , rate =    0.000666667
* tradeByTargetAmount: input =  15000.0 USDC, output =      10.000028 ETH , rate =    0.000666668
* tradeByTargetAmount: input = 150000.0 USDC, output =     100.002753 ETH , rate =    0.000666685


In [7]:
## Flip the pair and the price ranges to quote everything in ETH per USDC

# Re-initialize to origin state for clarity / readability of output
Sim = CarbonSimulatorUI(pair="USDC/ETH", verbose=False, matching_method='exact', raiseonerror=True)
Sim.add_strategy('USDC', Decimal(1000000000), 1/Decimal(1500), 1/Decimal(1000), 0, None, None)

# Now perform route by target trade
Sim.trader_buys('USDC',Decimal(1500), execute=False)
Sim.trader_buys('USDC',Decimal(15000), execute=False)
Sim.trader_buys('USDC',Decimal(150000), execute=False)
results = Sim.state()['trades']
assert(f"{results[results.uid=='0']['amt2'].values[0]:.5f}" == "1.00000")
assert(f"{results[results.uid=='1']['amt2'].values[0]:.5f}" == "10.00003")
assert(f"{results[results.uid=='2']['amt2'].values[0]:.5f}" == "100.00275")

# Note that the results are not quite as expected (per Barak's output in bullets above, where price=0.00673 matches but the others do not)
results

uid  id subid                              note   aggr   exec limitfail  \
0  0.0   0     0                          route #0  False  False      None   
0    0   0     A      AMM sells 1500USDC buys 1ETH   True  False      None   
0  1.0   1     0                          route #0  False  False      None   
0    1   1     A    AMM sells 15000USDC buys 10ETH   True  False      None   
0  2.0   2     0                          route #0  False  False      None   
0    2   2     A  AMM sells 150000USDC buys 100ETH   True  False      None   

       amt1  tkn1        amt2 tkn2     pair routeix  nroutes     price  \
0    1500.0  USDC    1.000000  ETH  USDCETH       0        1  0.000667   
0    1500.0  USDC    1.000000  ETH  USDCETH     [0]        1  0.000667   
0   15000.0  USDC   10.000028  ETH  USDCETH       0        1  0.000667   
0   15000.0  USDC   10.000028  ETH  USDCETH     [0]        1  0.000667   
0  150000.0  USDC  100.002753  ETH  USDCETH       0        1  0.000667   
0  150000.0  USDC  100.002753  ETH  USDCETH     [0]        1  0.000667   

         p_unit  
0  ETH per USDC  
0  ETH per USDC  
0  ETH per USDC  
0  ETH per USDC  
0  ETH per USDC  
0  ETH per USDC

In [8]:
## Flip the pair and the price ranges to quote everything in ETH per USDC

# Re-initialize to origin state for clarity / readability of output
FastSim = CarbonSimulatorUI(pair="USDC/ETH", verbose=False, matching_method='fast', raiseonerror=True)
FastSim.add_strategy('USDC', Decimal(1000000000), 1/Decimal(1500), 1/Decimal(1000), 0, None, None)

# Now perform route by target trade
FastSim.trader_buys('USDC',Decimal(1500), execute=False)
FastSim.trader_buys('USDC',Decimal(15000), execute=False)
FastSim.trader_buys('USDC',Decimal(150000), execute=False)
results = FastSim.state()['trades']
assert(f"{results[results.uid=='0']['amt2'].values[0]:.5f}" == "1.00000")
assert(f"{results[results.uid=='1']['amt2'].values[0]:.5f}" == "10.00003")
assert(f"{results[results.uid=='2']['amt2'].values[0]:.5f}" == "100.00275")
# Note that the results are not quite as expected (per Barak's output in bullets above, where price=0.00673 matches but the others do not)
results

uid  id subid                              note   aggr   exec limitfail  \
0  0.0   0     0                          route #0  False  False      None   
0    0   0     A      AMM sells 1500USDC buys 1ETH   True  False      None   
0  1.0   1     0                          route #0  False  False      None   
0    1   1     A    AMM sells 15000USDC buys 10ETH   True  False      None   
0  2.0   2     0                          route #0  False  False      None   
0    2   2     A  AMM sells 150000USDC buys 100ETH   True  False      None   

       amt1  tkn1        amt2 tkn2     pair routeix  nroutes     price  \
0    1500.0  USDC    1.000000  ETH  USDCETH       0        1  0.000667   
0    1500.0  USDC    1.000000  ETH  USDCETH     [0]        1  0.000667   
0   15000.0  USDC   10.000028  ETH  USDCETH       0        1  0.000667   
0   15000.0  USDC   10.000028  ETH  USDCETH     [0]        1  0.000667   
0  150000.0  USDC  100.002753  ETH  USDCETH       0        1  0.000667   
0  150000.0  USDC  100.002753  ETH  USDCETH     [0]        1  0.000667   

         p_unit  
0  ETH per USDC  
0  ETH per USDC  
0  ETH per USDC  
0  ETH per USDC  
0  ETH per USDC  
0  ETH per USDC

In [9]:
[1/x for x in results.price]

[1499.9995871176138,
 1499.9995871176138,
 1499.995871173015,
 1499.995871173015,
 1499.9587117307021,
 1499.9587117307021]

#### Flipped the pair

In [10]:
# Re-initialize to origin state for clarity / readability of output
Sim = CarbonSimulatorUI(pair="ETH/USDC", verbose=False, matching_method='exact', raiseonerror=True)
Sim.add_strategy('USDC', Decimal(1000000000), Decimal(1500), Decimal(1000), 0, None, None)

# Now perform route by target trade
Sim.trader_buys('USDC',Decimal(1500), execute=False)
Sim.trader_buys('USDC',Decimal(15000), execute=False)
Sim.trader_buys('USDC',Decimal(150000), execute=False)
results = Sim.state()['trades']
assert(f"{results[results.uid=='0']['amt2'].values[0]:.5f}" == "1.00000")
assert(f"{results[results.uid=='1']['amt2'].values[0]:.5f}" == "10.00003")
assert(f"{results[results.uid=='2']['amt2'].values[0]:.5f}" == "100.00275")
# Note that the results are not quite as expected (per Barak's output in bullets above, where price=0.00673 matches but the others do not)
results

uid  id subid                              note   aggr   exec limitfail  \
0  0.0   0     0                          route #0  False  False      None   
0    0   0     A      AMM sells 1500USDC buys 1ETH   True  False      None   
0  1.0   1     0                          route #0  False  False      None   
0    1   1     A    AMM sells 15000USDC buys 10ETH   True  False      None   
0  2.0   2     0                          route #0  False  False      None   
0    2   2     A  AMM sells 150000USDC buys 100ETH   True  False      None   

       amt1  tkn1        amt2 tkn2     pair routeix  nroutes        price  \
0    1500.0  USDC    1.000000  ETH  ETHUSDC       0        1  1499.999587   
0    1500.0  USDC    1.000000  ETH  ETHUSDC     [0]        1  1499.999587   
0   15000.0  USDC   10.000028  ETH  ETHUSDC       0        1  1499.995871   
0   15000.0  USDC   10.000028  ETH  ETHUSDC     [0]        1  1499.995871   
0  150000.0  USDC  100.002753  ETH  ETHUSDC       0        1  1499.958712   
0  150000.0  USDC  100.002753  ETH  ETHUSDC     [0]        1  1499.958712   

         p_unit  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH

In [11]:
[1/float(x) for x in results.price]

[0.0006666668501699999,
 0.0006666668501699999,
 0.0006666685017059333,
 0.0006666685017059333,
 0.0006666850175136933,
 0.0006666850175136933]

In [12]:
# Re-initialize to origin state for clarity / readability of output
FastSim = CarbonSimulatorUI(pair="ETH/USDC", verbose=False, matching_method='fast', raiseonerror=True)
FastSim.add_strategy('USDC', Decimal(1000000000), Decimal(1500), Decimal(1000), 0, None, None)

# Now perform route by target trade
FastSim.trader_buys('USDC',Decimal(1500), execute=False)
FastSim.trader_buys('USDC',Decimal(15000), execute=False)
FastSim.trader_buys('USDC',Decimal(150000), execute=False)
results = FastSim.state()['trades']
assert(f"{results[results.uid=='0']['amt2'].values[0]:.5f}" == "1.00000")
assert(f"{results[results.uid=='1']['amt2'].values[0]:.5f}" == "10.00003")
assert(f"{results[results.uid=='2']['amt2'].values[0]:.5f}" == "100.00275")
# Note that the results are not quite as expected (per Barak's output in bullets above, where price=0.00673 matches but the others do not)
results

uid  id subid                              note   aggr   exec limitfail  \
0  0.0   0     0                          route #0  False  False      None   
0    0   0     A      AMM sells 1500USDC buys 1ETH   True  False      None   
0  1.0   1     0                          route #0  False  False      None   
0    1   1     A    AMM sells 15000USDC buys 10ETH   True  False      None   
0  2.0   2     0                          route #0  False  False      None   
0    2   2     A  AMM sells 150000USDC buys 100ETH   True  False      None   

       amt1  tkn1        amt2 tkn2     pair routeix  nroutes        price  \
0    1500.0  USDC    1.000000  ETH  ETHUSDC       0        1  1499.999587   
0    1500.0  USDC    1.000000  ETH  ETHUSDC     [0]        1  1499.999587   
0   15000.0  USDC   10.000028  ETH  ETHUSDC       0        1  1499.995871   
0   15000.0  USDC   10.000028  ETH  ETHUSDC     [0]        1  1499.995871   
0  150000.0  USDC  100.002753  ETH  ETHUSDC       0        1  1499.958712   
0  150000.0  USDC  100.002753  ETH  ETHUSDC     [0]        1  1499.958712   

         p_unit  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH  
0  USDC per ETH

In [13]:
[1/x for x in results.price]

[0.0006666668501699999,
 0.0006666668501699999,
 0.0006666685017059332,
 0.0006666685017059332,
 0.0006666850175136933,
 0.0006666850175136933]